# Generated by Django 4.2.3 on 2023-08-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='date',
        ),
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.CharField(max_length=10000),
        ),
    ]
