# Generated by Django 4.2.3 on 2023-08-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_image_date_alter_image_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
